### ISSUE TITLE
Unsupported or unrecognized SSL message

### ISSUE THREAD

**Issue by aiden-sjeefr** [Mcpoowl/sFTPs#3]
I'm having issues using the ftps feature of the module. I've worked with SFTP, but the client insists with FTPS. Regardless of which FTPS service I use, whether it's the client or the test service at [Rebex](https://test.rebex.net/), I keep getting the error message `Unsupported or unrecognized SSL message` (see full log below). Filezilla, on the other hand, has absolutely no problem.

Little big digging into the Java action and Googling the issue made me think of updating the .jar files of at least the ApacheCommons, but without any success as the issue persists.

Unless there is a working FTPS alternative module, please help me out :)

- - -

**Project Details**:
Mendix app version: 9.12.4, started on 9.6.0
Module version: 3.0.0

- - - 

> javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:439)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:184)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at org.apache.commons.net.ftp.FTPSClient.sslNegotiation(FTPSClient.java:283)
	at org.apache.commons.net.ftp.FTPSClient._connectAction_(FTPSClient.java:219)
	at org.apache.commons.net.SocketClient._connect(SocketClient.java:254)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:212)
	at sftps.helpers.FTPSConnection.execute(FTPSConnection.java:77)
	at sftps.actions.JA_GetFileList.executeAction(JA_GetFileList.java:63)
	at sftps.actions.JA_GetFileList.executeAction(JA_GetFileList.java:29)
	--- Cut off by OP as the rest seems irrelevant ---

**Comment by aiden-sjeefr** [comment]
Update: I've disabled all libraries in Mendix and toggled them one by one, according to the error log during deployment, untill only about 25% of all libraries were ticked and the app ran. Yet, still the same error message.

My Userlib folder contains the `commons-net-3.8.0.jar` file, whereas according to their own Jira in 3.7.1. this SSL message was fixed. When I disable that library, the app does not run. If I do toggle it, the app runs, but I still cannot use FTPS. Seems something is still going wrong.

**Comment by aiden-sjeefr** [comment]
Another update: I've created two seperate apps with the 'Blank Web app' template, on Mx 9.12.4 and 8.18.15 and directly thereafter installed the SFTPS module, nothing else. Of course set up the configuration and tried to connect. Same error message. I've tested both with FTP and FTPS on various providers, but FTP always works and FTPS never.

I've retried replacing/updating the .jar files and ended up with the latest version of jsch (0.1.55), commons-io(2.11.0) and commons-net(3.8.0). No fix.

I really believe there is something wrong with the core of the module.
